### PR TITLE
Use CMake and support clients using CMake

### LINKED ISSUE #3: Interest in Adding a Build System?
Is there any desire to add a build system to this project (i.e. CMake) and/or unit tests? Just trying to gauge where this project will go in the future.

### PR DESCRIPTION
**Pull request by friendlyanon**
Fixes #3 and some compiler warnings. Moved `WIN32_LEAN_AND_MEAN` to the build system.

I have also seen someone wanting to add Linux support, which should be easy by just extending the `if()`.

For anyone wanting to add tests to this, you'll just have to add these lines at the end:

```cmake
include(CTest)
if(BUILD_TESTING)
  add_executable(CrashlogsTests test.cpp)
  target_link_libraries(CrashlogsTests PRIVATE Crashlogs)
  add_test(NAME CrashlogsTests COMMAND CrashlogsTests)
endif()
```

Lines 12-16 make it possible for users to consume this project like so:

```cmake
find_package(Crashlogs REQUIRED)
target_link_libraries(Dog PRIVATE Crashlogs::Crashlogs)
```

```cpp
#include <crashlogs.h>

...
```

Vendoring via `add_subdirectory` (or anything that wraps it) is NOT supported. That would require even more code for no good reason.

### CODE REVIEW

**Comment by friendlyanon** [comment]
Oops, sticky shift key.

**Comment by TylerGlaiel** [comment]
leave WIN32_LEAN_AND_MEAN in the file and I'll add it (reasoning: cmake should be completely optional)

**Comment by friendlyanon** [comment]
Would also be worth seeing where #4 goes. I could just rebase and adapt changes from that instead of having to do 2 PRs.

**Comment by TylerGlaiel** [comment]
sure, cmake is entirely irrelevant to me so if you wanna wait till mac/linux support is in to add it then let me know. im not gonna maintain cmakelists.txt myself, someone will have to update it when new platforms are added

**Comment by friendlyanon** [comment]
Seems the other PR went dormant. You could accept this then I can review CMake related changes in the other PR if it ever gets picked back up.

**Comment by TylerGlaiel** [comment]
Cmakelists added for those who really wanted it

**Pull request merged**
